import Head from 'next/head'

import Navbar from '../components/Navbar';
import App from '../components/App';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hackathon Challenge 6</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <App />
      </main>
    </div>
  )
}
